version: '3.8'

services:
  backend:
    image: node:20-alpine
    restart: unless-stopped
    working_dir: /app
    command: sh -c "cp backend-package.json package.json && npm install && node backend-server.mjs"
    volumes:
      - ./:/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    labels:
      - "easypanel.enable=true"
      - "easypanel.display_name=InstaFlow Backend"
      - "easypanel.icon=https://cdn-icons-png.flaticon.com/512/174/174855.png"
